# Generated by Django 3.0 on 2022-04-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.CharField(choices=[('1', 'Internal'), ('2', 'External')], default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='linktoform',
            field=models.URLField(default='www.google.com', max_length=300),
            preserve_default=False,
        ),
    ]
