# Generated by Django 3.0 on 2022-05-05 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0005_shortlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='shortlist',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shortlist',
            name='shortlister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicantofficer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicantin', to='portal.Applicant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobin', to='portal.Job')),
                ('officerin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
